services:
  exegol-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exegol-nginx
    ports:
      - "9000:80"
    volumes:
      - /opt/exegol-tars:/opt/exegol-tars:ro
    restart: unless-stopped

