services:
  exegol-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exegol-nginx
    ports:
      - "80:80"
    volumes:
      - /exu/exegol-update-server/exu-tars:/exu/exegol-update-server/exu-tars:ro
    restart: unless-stopped

